name: CI

on: [push, pull_request]

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      # build with TLS just for compilatoin coverage
      run: make BUILD_TLS=yes
    - name: test
      run: |
        sudo apt-get install tcl8.6
        ./runtest --verbose
    - name: module api test
      run: ./runtest-moduleapi --verbose

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

  build-32bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make 32bit

  build-libc-malloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc

  build-memkind-malloc:
    runs-on: ${{ matrix.os }}
    name: Building memkind daxctl ${{ matrix.daxctl }} | hwloc ${{ matrix.hwloc }} | ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        daxctl: [false, true]
        hwloc: [false, true]
        malloc: [memkind, memkind_memtier]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialize memkind repo
      run: git submodule update --init

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install autoconf libnuma-dev

    - name: Install daxctl dependency
      run: |
        if [ "${{ matrix.daxctl }}" == true ]; then
          sudo apt install libdaxctl-dev
        else
          echo "Skipping daxctl installation"
        fi

    - name: Install hwloc dependency
      run: |
        if [ "${{ matrix.hwloc }}" == true ]; then
          ./deps/memkind/utils/docker/docker_install_hwloc.sh
        else
          echo "Skipping hwloc installation"
        fi

    - name: Build memkeydb
      run: |
        make MALLOC=${{ matrix.malloc }}
